Feature branch
Abidoyinsola1/apple-website-page pull request #1
Opened 2020-06-11 15:38 UTC by Abidoyinsola1

At HTML changes:
 - Added header, main and footer tag sections of the page.

At CSS changes: 
- Styled the header tag, including the nav.
- Added background image
- Styled main section
- Styled  the footer section

These were done to be as the given webpage for the project.

2020-06-11 17:29 UTC, tirthajyoti-ghosh commented
# Pull Request under review by T. Ghosh (TSE)

2020-06-11 17:49 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🚨

## Hello @Abidoyinsola1 and @somoye123 🖐
## Awesome project team ✨👌

### However, we still need to work on some changes before we can move ahead.

- The `nav` section should have 9 elements including the input field. Currently, you have only 8. Also, add a bit more space above it and decrease its size to match the original.
  
   Right now 👇

   ![Annotation 2020-06-11 231227](https://user-images.githubusercontent.com/57726348/84421606-6f619180-ac39-11ea-8db5-f39f71f7ffbb.jpg)

   Original 👇
  
   ![Annotation 2020-06-11 231253](https://user-images.githubusercontent.com/57726348/84421639-7dafad80-ac39-11ea-917f-75f49a8200b9.jpg)

-  Decrease the size and font-weight of `header-text` to match the original.

*I have also left some reviews below. Be sure to check them.*

2020-06-11 17:51 UTC, tirthajyoti-ghosh commented on index.html
> +        <div class="nav-items"><a href="">Support</a></div>
- The `href` attribute must not be empty. Add `#` -> `href="#"`

2020-06-11 17:51 UTC, tirthajyoti-ghosh commented on index.html
> +          <li><a href="">Contact Us</a></li>
- The `href` attribute must not be empty. Add `#` -> `href="#"`

2020-06-11 17:52 UTC, tirthajyoti-ghosh commented on index.html
> +      <a href="#!"><img src="asset/image/apple-4.jpg" alt="" /></a>
- Remove `!` in `href`. It should be -> `href="#"`

2020-06-11 17:52 UTC, tirthajyoti-ghosh commented on index.html
> +          <a href="#!"> reseller</a>.
- Remove `!` in `href`. It should be -> `href="#"`

2020-06-11 17:53 UTC, tirthajyoti-ghosh commented on index.html
> +          an <a href=""> Apple Retail Store</a>, or find a
- The `href` attribute must not be empty. Add `#` -> `href="#"`

2020-06-11 17:53 UTC, tirthajyoti-ghosh reviewed
Apply these changes and request another code review.

Happy coding 👨‍💻

2020-06-11 19:36 UTC, BrittanyBlake commented
### Pull Request under review by Brittany Blake (TSE)

2020-06-11 19:43 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi Team! 👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] The search bar in your navigation is extending outside of the navigation bar. Please compare your clone with the original page and fix this.
Your clone 👇 
![Screen Shot 2020-06-11 at 9 33 04 PM](https://user-images.githubusercontent.com/48804258/84431779-26efa700-ac2c-11ea-8f83-4db99788abe3.png)
The original page 👇 
![Screen Shot 2020-06-11 at 9 39 41 PM](https://user-images.githubusercontent.com/48804258/84431781-2820d400-ac2c-11ea-9890-026614e2877e.png)

- [ ] As was requested by the previous TSE, please decrease your font-size and weight for `header-text`.
The original page 👇 
![Screen Shot 2020-06-11 at 9 41 52 PM](https://user-images.githubusercontent.com/48804258/84431925-63bb9e00-ac2c-11ea-8f2f-4e2186eadb47.png)
Your clone 👇 
![Screen Shot 2020-06-11 at 9 41 57 PM](https://user-images.githubusercontent.com/48804258/84431928-66b68e80-ac2c-11ea-9ade-bd405888ccea.png)




****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-06-12 09:37 UTC, andresporras3423 commented
### **Pull Request Under Review By Oscar Russi (TSE)**

2020-06-12 09:48 UTC, andresporras3423 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello @Abidoyinsola1 @somoye123** 
Amazing job :tada: :tada: :tada:  you have met all the requirements for this project
Now you are ready to continue with your next challenge :muscle: 
Don't forget to merge with the master branch

Keep going like this  :clap: :clap:

Oscar Andrés Russi Porras
(for any question you can contact me in slack as @oscarporras02)

2020-06-12 10:10 UTC, merged